Repository DeveloperAcademy-POSTECH/MC3-Team8-Aing, pull requests merged in 2023-07, with the labels that each got.

#5 [Setting] 프로젝트 세팅
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Global/Extension/Color+.swift
  Diptych/Diptych/Global/Extension/Font+.swift
  Diptych/Diptych/Info.plist
  Diptych/Diptych/Presentation/Archive/View/ArchiveView.swift
  Diptych/Diptych/Presentation/Common/ContentView.swift
  Diptych/Diptych/Presentation/Common/DiptychTabView.swift
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Resources/AssetCatalog/Assets.xcassets/AppIcon.appiconset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Assets.xcassets/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/DarkGray.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/LightGray.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/OffBlack.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/OffBlack50.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/OffWhite.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/Red.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/Salmon.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/SystemBlack.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/SystemBlack85.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/SystemWhite.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgArchiveTab.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgArchiveTab.imageset/imgArchiveTab@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgArchiveTab.imageset/imgArchiveTab@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgArchiveTab.imageset/imgArchiveTab@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgArchiveTabSelected.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgArchiveTabSelected.imageset/imgArchiveTabSelected@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgArchiveTabSelected.imageset/imgArchiveTabSelected@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgArchiveTabSelected.imageset/imgArchiveTabSelected@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgProfileTab.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgProfileTab.imageset/imgUserTab@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgProfileTab.imageset/imgUserTab@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgProfileTab.imageset/imgUserTab@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgProfileTabSelected.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgProfileTabSelected.imageset/imgUserTabSelected@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgProfileTabSelected.imageset/imgUserTabSelected@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgProfileTabSelected.imageset/imgUserTabSelected@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgTodayDiptychTab.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgTodayDiptychTab.imageset/imgTodayDiptychTab@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgTodayDiptychTab.imageset/imgTodayDiptychTab@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgTodayDiptychTab.imageset/imgTodayDiptychTab@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgTodayDiptychTabSelected.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgTodayDiptychTabSelected.imageset/imgTodayDiptychTabSelected@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgTodayDiptychTabSelected.imageset/imgTodayDiptychTabSelected@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TabBar/imgTodayDiptychTabSelected.imageset/imgTodayDiptychTabSelected@3x.png
  Diptych/Diptych/Resources/Font/Pretendard-Black.otf
  Diptych/Diptych/Resources/Font/Pretendard-Bold.otf
  Diptych/Diptych/Resources/Font/Pretendard-ExtraBold.otf
  Diptych/Diptych/Resources/Font/Pretendard-ExtraLight.otf
  Diptych/Diptych/Resources/Font/Pretendard-Light.otf
  Diptych/Diptych/Resources/Font/Pretendard-Medium.otf
  Diptych/Diptych/Resources/Font/Pretendard-Regular.otf
  Diptych/Diptych/Resources/Font/Pretendard-SemiBold.otf
  Diptych/Diptych/Resources/Font/Pretendard-Thin.otf
  Diptych/Diptych/Util/NameSpace/PretendardType.swift
Labels: 소다, Setting

#12 [Feat] #9 - 앨범 보기 리스트 - 기본 레이아웃 작성
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/Archive/View/AlbumListView.swift
  Diptych/Diptych/Presentation/Archive/View/AlbumNavigationView.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_1.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_1.imageset/DummyThumbnail_1.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_2.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_2.imageset/DummyThumbnail_2.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_3.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_3.imageset/DummyThumbnail_3.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_4.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_4.imageset/DummyThumbnail_4.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_5.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_5.imageset/DummyThumbnail_5.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_6.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_6.imageset/DummyThumbnail_6.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_7.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_7.imageset/DummyThumbnail_7.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_8.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_8.imageset/DummyThumbnail_8.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_9.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Dummy Image/DummyThumbnail_9.imageset/DummyThumbnail_9.png
Labels: Feat, 클리프

#14 [Feat] #7 - Firebase 설치 및 기본 세팅
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Info.plist
  Diptych/Diptych/Presentation/Auth/AuthViewModel.swift
  Diptych/Diptych/Presentation/Auth/LogInView.swift
  Diptych/Diptych/Presentation/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/OnBoarding/OnBoardingView.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/diptych_sample1.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/diptych_sample1.imageset/diptych_sample1.jpeg
  Diptych/GoogleService-Info.plist
Labels: Add, 베니

#16 [Design] #8 - 오늘딥틱뷰 레이아웃 구현
  1
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/Presentation/Common/DiptychTabView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/WeeklyCalenderView.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgDiptychCamera.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgDiptychCamera.imageset/imgDiptychCamera.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgDiptychCamera.imageset/imgDiptychCamera@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgDiptychCamera.imageset/imgDiptychCamera@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgDiptychRetry.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgDiptychRetry.imageset/imgDiptychRetry@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgDiptychRetry.imageset/imgDiptychRetry@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgDiptychRetry.imageset/imgDiptychRetry@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgNotification.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgNotification.imageset/Notification@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgNotification.imageset/Notification@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgNotification.imageset/Notification@3x.png
Labels: Design, 소다

#19 Feat/#6
  1
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/Diptych.entitlements
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Model/DiptychUser.swift
  Diptych/Diptych/Presentation/Auth/AuthViewModel.swift
  Diptych/Diptych/Presentation/Auth/AuthenticationViewModel.swift
  Diptych/Diptych/Presentation/Auth/EmailVerificationView.swift
  Diptych/Diptych/Presentation/Auth/LogInView.swift
  Diptych/Diptych/Presentation/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/Matching/CouplingViewModel.swift
  Diptych/Diptych/Presentation/OnBoarding/OnBoardingView.swift
Labels: Feat, 베니

#23 [Feat] #21 - 카메라 추가 (서버 부분 제외)
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/Global/Extension/UIDevice+.swift
  Diptych/Diptych/Global/Extension/UIImage+.swift
  Diptych/Diptych/Info.plist
  Diptych/Diptych/Presentation/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/OnBoarding/OnBoardingView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/CameraRepresentableView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraStoryboard.storyboard
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraViewController.swift
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/SystemRed.colorset/Contents.json~HEAD
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/SystemRed.colorset/Contents.json~develop
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/SystemSalmon.colorset/Contents.json~HEAD
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/SystemSalmon.colorset/Contents.json~develop
  Diptych/Diptych/Util/TransformImageBasedOnContainerView.swift
Labels: Feat

#32 assets 파일 추가
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_Logo.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_Logo.imageset/Temp_Logo.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_imagePreviewButton.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_imagePreviewButton.imageset/Temp_imagePreviewButton.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_imgGuide.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_imgGuide.imageset/Temp_imgGuide.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_imgTransparentGuide.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_imgTransparentGuide.imageset/guide@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_imgTransparentGuide.imageset/guide@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Temp_imgTransparentGuide.imageset/guide@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgBackButton.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgBackButton.imageset/back@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgBackButton.imageset/back@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgBackButton.imageset/back@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCircleCheckButton.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCircleCheckButton.imageset/check@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCircleCheckButton.imageset/check@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCircleCheckButton.imageset/check@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCloseButton.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCloseButton.imageset/imgCloseButton.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCloseButton.imageset/x@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCloseButton.imageset/x@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgFlashButton.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgFlashButton.imageset/flash@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgFlashButton.imageset/flash@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgFlashButton.imageset/imgFlashButton.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgShutterButton.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgShutterButton.imageset/imgShutterButton.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgShutterButton.imageset/shutter@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgShutterButton.imageset/shutter@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgToggleButton.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgToggleButton.imageset/change@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgToggleButton.imageset/change@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgToggleButton.imageset/imgToggleButton.png
Labels: Fix, Add

#34 Feat/#18
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Global/Extension/Date+.swift
  Diptych/Diptych/Model/DiptychUser.swift
  Diptych/Diptych/Presentation/Common/DiptychTabView.swift
  Diptych/Diptych/Presentation/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/Matching/CouplingViewModel.swift
  Diptych/Diptych/Presentation/OnBoarding/OnBoardingView.swift
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Presentation/User/Auth/.gitkeep
  Diptych/Diptych/Presentation/User/Auth/AuthenticationViewModel.swift
  Diptych/Diptych/Presentation/User/Auth/EmailVerificationView.swift
  Diptych/Diptych/Presentation/User/Auth/LoadingVerificationView.swift
  Diptych/Diptych/Presentation/User/Auth/LogInFlowView.swift
  Diptych/Diptych/Presentation/User/Auth/LogInView.swift
  Diptych/Diptych/Presentation/User/Auth/ProfileSettingView.swift
  Diptych/Diptych/Presentation/User/Auth/SignUpFlowView.swift
  Diptych/Diptych/Presentation/User/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/User/Matching/.gitkeep
  Diptych/Diptych/Presentation/User/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/User/Matching/CouplingViewModel.swift
  Diptych/Diptych/Presentation/User/Matching/TestView.swift
  Diptych/Diptych/Presentation/User/Matching/TestViewModel.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
Labels: Feat, 베니

#33 [Design] #28 - 프로필 뷰 레이아웃 제작
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/heart.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/heart.imageset/Heart.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/heart.imageset/Heart@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/heart.imageset/Heart@3x.png
Labels: Design, 나일라

#37 Feat/#17
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych.xcodeproj/xcshareddata/xcschemes/Diptych.xcscheme
  Diptych/Diptych/Presentation/Common/DiptychTabView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/WeeklyCalenderView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
Labels: Feat, 소다

#41 Feat/#18
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/Model/DiptychAlbum.swift
  Diptych/Diptych/Model/DiptychUser.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
Labels: Add, 베니

#43 [Feat] #38 - 오늘 업로드 상태에 따라 이미지 상태 구분
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Data/Manager/CalendarManager.swift
  Diptych/Diptych/Presentation/TodayDiptych/Model/Content.swift
  Diptych/Diptych/Presentation/TodayDiptych/Model/Photo.swift
  Diptych/Diptych/Presentation/TodayDiptych/Model/WeeklyData.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgRetry.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgRetry.imageset/Group 231@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgRetry.imageset/Group 231@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/imgRetry.imageset/Group 231@3x.png
Labels: Feat, 소다

#47 Feat/#44
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/DiptychSplashLogo.json
  Diptych/Diptych/LottieView.swift
  Diptych/Diptych/Model/DiptychAlbum.swift
  Diptych/Diptych/Presentation/OnBoarding/OnBoardingView.swift
  Diptych/Diptych/Presentation/User/Auth/AuthenticationViewModel.swift
  Diptych/Diptych/Presentation/User/Auth/EmailVerificationView.swift
  Diptych/Diptych/Presentation/User/Auth/LoadingVerificationView.swift
  Diptych/Diptych/Presentation/User/Auth/LogInFlowView.swift
  Diptych/Diptych/Presentation/User/Auth/LogInView.swift
  Diptych/Diptych/Presentation/User/Auth/SignUpFlowView.swift
  Diptych/Diptych/Presentation/User/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/User/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/User/Matching/CouplingViewModel.swift
  Diptych/Diptych/Presentation/User/Matching/ProfileSettingView.swift
  Diptych/Diptych/Presentation/User/Matching/TestView.swift
  Diptych/Diptych/Presentation/User/Matching/TestViewModel.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
Labels: Design, Fix, Add, 베니

#49 [Fix] #45 - 일주일 캘린더 로직 변경
  Diptych/Diptych/Presentation/TodayDiptych/Model/WeeklyData.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
Labels: Fix

#52 [Feat] #50 - 오늘딥틱뷰 상세 수정
  1
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
Labels: Feat, 소다

#54 Feat/#44
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/DiptychSplashLogo3sec.json
  Diptych/Diptych/Info.plist
  Diptych/Diptych/LottieView.swift
  Diptych/Diptych/Presentation/OnBoarding/OnBoardingView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/OnBoardingViewImage.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/OnBoardingViewImage.imageset/OnBoardingViewImage.png
Labels: Design, Fix, Add, 베니

#56 [Feat] #51 - 프로필 뷰에 유저 데이터 불러오기
  Diptych/Diptych/Presentation/Archive/View/PhotoDetailView.swift
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/comment.imageset/Comment.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/comment.imageset/Comment@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/comment.imageset/Comment@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/comment.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/download.imageset/Download@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/download.imageset/Download@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/download.imageset/Download@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/send.imageset/Send.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/send.imageset/Send@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/send.imageset/Send@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/upload.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/upload.imageset/Upload.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/upload.imageset/Upload@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/upload.imageset/Upload@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/whiteHeart.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/whiteHeart.imageset/Heart.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/whiteHeart.imageset/Heart@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/whiteHeart.imageset/Heart@3x.png
Labels: Feat, 나일라

#57 [Feat] #48 - 카메라 업로드 (3)
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Global/Extension/UIColor+.swift
  Diptych/Diptych/Presentation/Common/LottieUIViews.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraStoryboard.storyboard
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraViewController.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCameraLoading.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCameraLoading.imageset/imgCameraLoading@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCameraLoading.imageset/imgCameraLoading@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCameraLoading.imageset/imgCameraLoading@3x.png
  Diptych/Diptych/Resources/LoadingLottie.json
  Diptych/Diptych/Util/FirebaseMananger.swift
Labels: Feat, Design, 클리프

#58 Feat/#44
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Info.plist
  Diptych/Diptych/Presentation/OnBoarding/OnBoardingView.swift
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
  Diptych/Diptych/Presentation/User/Auth/LogInView.swift
  Diptych/Diptych/Presentation/User/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/User/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/User/Matching/ProfileSettingView.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/OnBoardingViewImage2.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/OnBoardingViewImage2.imageset/OnBoardingViewImage2.png
Labels: Fix, 베니

#60 [Feat] #46 - 사진 상세 뷰 및 프로필 뷰 수정
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/Archive/View/PhotoDetailView.swift
  Diptych/Diptych/Presentation/Archive/View/ShareSheetView.swift
Labels: Feat, 나일라

#61 Feat/#44
  Diptych/Diptych/Presentation/User/Auth/LoadingVerificationView.swift
  Diptych/Diptych/Presentation/User/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/User/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/User/Matching/ProfileSettingView.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
Labels: Fix, 베니

#65 [Fix] #53 - todayPhoto가 nil이 되는 문제 해결
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Info.plist
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraViewController.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
  Diptych/Diptych/Presentation/User/Auth/LogInView.swift
Labels: Fix, 소다

#66 [Feat] #64 - 라이브러리 버튼 이미지에 기기에 저장된 최신 사진 나오도록 함
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraStoryboard.storyboard
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraViewController.swift
Labels: Feat, 클리프

#68 Feat/#63
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/Components/SecureInputView.swift
  Diptych/Diptych/Presentation/Common/DiptychTabView.swift
  Diptych/Diptych/Presentation/OnBoarding/OnBoardingView.swift
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
  Diptych/Diptych/Presentation/User/Auth/LoadingVerificationView.swift
  Diptych/Diptych/Presentation/User/Auth/LogInView.swift
  Diptych/Diptych/Presentation/User/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/User/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/User/Matching/ProfileSettingView.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
Labels: Feat, Design, Fix, 베니

#69 [Feat] #57 - 앨범 생성일 이후에 질문 순서대로 나오게 하기
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
Labels: Feat, 소다

#76 [Fix] #75 - 오늘딥틱뷰 디자인 변경
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/WeeklyCalenderView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
Labels: Fix, 소다

#84 [Design] #81 - 카메라 디자인 변경 및 안정화
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraStoryboard.storyboard
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraViewController.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-circle.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-circle.imageset/Group 243@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-circle.imageset/Group 243@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-circle.imageset/Group 243@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-couple_standing.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-couple_standing.imageset/Group 252@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-couple_standing.imageset/Group 252@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-couple_standing.imageset/Group 252@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-diamond.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-diamond.imageset/Group 250@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-diamond.imageset/Group 250@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-diamond.imageset/Group 250@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-heart.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-heart.imageset/Group 249@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-heart.imageset/Group 249@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-heart.imageset/Group 249@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-horizontal_line.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-horizontal_line.imageset/Group 246@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-horizontal_line.imageset/Group 246@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-horizontal_line.imageset/Group 246@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-person.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-person.imageset/Group 251@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-person.imageset/Group 251@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-person.imageset/Group 251@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-square.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-square.imageset/Group 245@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-square.imageset/Group 245@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-square.imageset/Group 245@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-vertical_line.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-vertical_line.imageset/Group 248@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-vertical_line.imageset/Group 248@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/Guidelines/GUIDELINE-vertical_line.imageset/Group 248@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCircleUploadButton.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCircleUploadButton.imageset/Group 345_button@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCircleUploadButton.imageset/Group 345_button@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Camera/imgCircleUploadButton.imageset/Group 345_button@3x.png
Labels: Design, Fix, 클리프
