Repository DeveloperAcademy-POSTECH/MC3-Team8-Aing, pull requests merged in 2023-10, with the labels that each got.

#123 [Design] #121 - 탭뷰 수정
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Model/DiptychAlbum.swift
  Diptych/Diptych/Model/DiptychUser.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CalendarScrollView.swift
  Diptych/Diptych/Presentation/Auth/View/LoadingVerificationView.swift
  Diptych/Diptych/Presentation/Auth/View/LoginView.swift
  Diptych/Diptych/Presentation/Auth/View/SignUpView.swift
  Diptych/Diptych/Presentation/Auth/ViewModel/UserViewModel.swift
  Diptych/Diptych/Presentation/Common/ArchiveTabView.swift
  Diptych/Diptych/Presentation/Common/DiptychTabView.swift
  Diptych/Diptych/Presentation/Matching/View/CouplingView.swift
  Diptych/Diptych/Presentation/Matching/View/ProfileSettingView.swift
  Diptych/Diptych/Presentation/NavigationBackButton.swift
  Diptych/Diptych/Presentation/OnBoarding/View/OnBoardingView.swift
  Diptych/Diptych/Presentation/Onboarding/View/OnboardingView.swift
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Presentation/SecureInputTextField.swift
  Diptych/Diptych/Presentation/SquareButton.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/User/View/Auth/LogInView.swift
  Diptych/Diptych/Resources/AssetCatalog/Colors.xcassets/KakaoLoginYellow.colorset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/icnApple.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/icnApple.imageset/icnApple@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/icnApple.imageset/icnApple@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/icnApple.imageset/icnApple@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/icnKakao.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/icnKakao.imageset/icnKakao@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/icnKakao.imageset/icnKakao@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Onboarding/icnKakao.imageset/icnKakao@3x.png
Labels: Design, 소다

#125 [Feat] #122 - action sheet - 유저 앨범에 저장하기
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Global/Extension/UIImage+.swift
  Diptych/Diptych/Presentation/Archive/View/Album/AlbumListView.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CalendarScrollView.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CalendarView.swift
  Diptych/Diptych/Presentation/Archive/View/QuestionList/QuestionListView.swift
  Diptych/Diptych/Presentation/Auth/View/LoginView.swift
  Diptych/Diptych/Presentation/Common/ArchiveTabView.swift
  Diptych/Diptych/Presentation/Onboarding/View/OnboardingView.swift
  Diptych/Diptych/Presentation/PhotoDetail/View/PhotoDetailView.swift
  Diptych/Diptych/Presentation/PhotoDetail/View/ShareSheetView.swift
Labels: Feat, 클리프

#126 [Design] #124 - 아카이빙 탭 질문함 뷰 추가
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/Archive/View/ArchiveTabView.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CalendarScrollView.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CalendarView.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/MonthlyCalendarView.swift
  Diptych/Diptych/Presentation/Archive/View/QuestionList/QuestionListView.swift
  Diptych/Diptych/Presentation/Archive/View/Questions/LikedQuestionCellView.swift
  Diptych/Diptych/Presentation/Archive/View/Questions/QuestionCellView.swift
  Diptych/Diptych/Presentation/Archive/View/Questions/QuestionListView.swift
  Diptych/Diptych/Presentation/Archive/ViewModel/ArchiveViewModel.swift
  Diptych/Diptych/Presentation/Common/ArchiveTabView.swift
  Diptych/Diptych/Presentation/LikeSegmentedControl.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnHeart.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnHeart.imageset/Heart@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnHeart.imageset/Heart@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnHeart.imageset/Heart@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnSearch.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnSearch.imageset/Icon@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnSearch.imageset/Icon@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnSearch.imageset/Icon@3x.png
Labels: Design, 소다

#129 [Feat] #128 - 질문 검색 기능 추가
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/Archive/View/Questions/QuestionListView.swift
  Diptych/Diptych/Presentation/Archive/ViewModel/QuestionListViewModel.swift
Labels: Feat, 소다

#132 [Refactor] #128 - guard문으로 변경
  Diptych/Diptych/Presentation/Archive/ViewModel/QuestionListViewModel.swift
Labels: Refactor, 소다

#133 [Design] #127 - 아카이빙 탭 앨범뷰 디자인 수정
  Diptych/Diptych/Presentation/Archive/View/Album/AlbumListView.swift
  Diptych/Diptych/Presentation/Archive/View/ArchiveTabView.swift
  Diptych/Diptych/Presentation/PhotoDetail/View/PhotoDetailView.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnLikedHeart.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnLikedHeart.imageset/Heart@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnLikedHeart.imageset/Heart@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Archive/icnLikedHeart.imageset/Heart@3x.png
Labels: Design, 소다

#136 [Feat] #135 - 댓글 뷰 추가
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Diptych/Diptych/Model/DiptychPhotoComment.swift
  Diptych/Diptych/Presentation/Archive/ViewModel/ArchiveViewModel.swift
  Diptych/Diptych/Presentation/Comment/View/CommentCell.swift
  Diptych/Diptych/Presentation/Comment/View/CommentListScrollView.swift
  Diptych/Diptych/Presentation/Comment/View/CommentView.swift
  Diptych/Diptych/Presentation/Comment/ViewModel/CommentViewModel.swift
  Diptych/Diptych/Presentation/PhotoDetail/View/PhotoDetailView.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Comment/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Comment/imgCommentUpload.imageset/Arrow upupload.svg
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Comment/imgCommentUpload.imageset/Contents.json
Labels: Feat, 클리프

#137 [Design] 이미지상세뷰 기기 대응
  Diptych/Diptych/Presentation/Archive/View/ArchiveTabView.swift
  Diptych/Diptych/Presentation/PhotoDetail/View/PhotoDetailView.swift
  Diptych/Diptych/Presentation/PhotoDetail/View/ShareSheetView.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Comment.imageset/Comment@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Comment.imageset/Comment@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Comment.imageset/Comment@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Comment.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/icnComment.imageset/Comment@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/icnComment.imageset/Comment@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/icnComment.imageset/Comment@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/icnComment.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/icnShareBox.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/icnShareBox.imageset/Share-box.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/icnShareBox.imageset/Share-box@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/icnShareBox.imageset/Share-box@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgComment.imageset/Comment.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgComment.imageset/Comment@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgComment.imageset/Comment@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgUpload.imageset/Upload.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgUpload.imageset/Upload@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgUpload.imageset/Upload@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Share-box.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Share-box.imageset/Share-box@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Share-box.imageset/Share-box@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Share-box.imageset/Share-box@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/icnComment.imageset/Comment@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/icnComment.imageset/Comment@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/icnComment.imageset/Comment@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/icnComment.imageset/Contents.json
Labels: Design, 소다
