Repository DeveloperAcademy-POSTECH/MC3-Team8-Aing, pull requests merged in 2023-08, with the labels that each got.

#85 [Feat] #83 - 오늘딥틱뷰 위클리 캘린더 로직 변경 및 디자인 수정 반영
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/TodayDiptych/View/DiptychCompleteAlertView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/WeeklyCalenderView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/icnXMark.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/icnXMark.imageset/Group 46@1x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/icnXMark.imageset/Group 46@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/TodayDiptych/icnXMark.imageset/Group 46@3x.png
Labels: Feat, 소다

#88 [Fix] #78 - 프로필 뷰 디자인 변경
  Diptych/Diptych/Presentation/Archive/View/PhotoDetailView.swift
  Diptych/Diptych/Presentation/Archive/View/ShareSheetView.swift
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgComment.imageset/Comment.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgComment.imageset/Comment@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgComment.imageset/Comment@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgComment.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgShareBox.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgShareBox.imageset/Share-box.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgShareBox.imageset/Share-box@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgShareBox.imageset/Share-box@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgUpload.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgUpload.imageset/Upload.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgUpload.imageset/Upload@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgUpload.imageset/Upload@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgWhiteHeart.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgWhiteHeart.imageset/Heart.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgWhiteHeart.imageset/Heart@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/PhotoDetail/imgWhiteHeart.imageset/Heart@3x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/imgHeart.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/imgHeart.imageset/Heart.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/imgHeart.imageset/Heart@2x.png
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/Profile/imgHeart.imageset/Heart@3x.png
Labels: Fix, 나일라

#89 [Design] #15 - 아이콘 추가, 질문함 삭제
  Diptych/Diptych/Presentation/Archive/View/PhotoDetailView.swift
  Diptych/Diptych/Presentation/Archive/ViewModel/ArchiveViewModel.swift
Labels: Design, 구피

#95 [Feat] PhotoDetailView 이미지 표시 최적화 (캐싱 등)
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/Archive/View/PhotoDetailView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraViewController.swift
  Diptych/Diptych/Util/FirebaseMananger.swift
  Diptych/Diptych/Util/ImageCacheManager.swift
Labels: Feat, 클리프

#96 [Design] #86 - 오늘딥틱뷰 디자인 최종 수정 (blur 제외)
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Presentation/Common/DiptychTabView2.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/DiptychCompleteAlertView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/DiptychCompleteAlertObject.swift
Labels: Design, 소다

#97 [Feat] #94 - 위클리 캘린더 로직 변경
  Diptych/Diptych/Presentation/TodayDiptych/Model/WeeklyData.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
Labels: Feat, 소다

#100 Add/#99
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Presentation/Archive/View/QuestionListView/QuestionListView.swift
  Diptych/Diptych/Presentation/Common/DiptychTabView2.swift
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/OnBoardingViewImage3.imageset/Contents.json
  Diptych/Diptych/Resources/AssetCatalog/Images.xcassets/OnBoardingViewImage3.imageset/OnBoardingViewImage3.png
  Diptych/GoogleService-Info-2.plist
Labels: Add, 베니

#101 Add/#99
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Presentation/User/UserViewModel.swift
Labels: Fix, 베니

#104 [Design] 카메라 보정 모드에서 줌핀치 가능 설명 추가
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraStoryboard.storyboard
  Diptych/Diptych/Presentation/TodayDiptych/ViewController/CameraViewController.swift
Labels: Design, 클리프

#109 [Chore] #108 - 폴더 구조 정리
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Data/Manager/FirebaseMananger.swift
  Diptych/Diptych/Data/Manager/ImageCacheManager.swift
  Diptych/Diptych/DiptychApp.swift
  Diptych/Diptych/Global/Extension/Date+.swift
  Diptych/Diptych/Global/Extension/Image+.swift
  Diptych/Diptych/Global/Extension/UIColor+.swift
  Diptych/Diptych/Global/Extension/UIDevice+.swift
  Diptych/Diptych/Global/Extension/UIImage+.swift
  Diptych/Diptych/Global/Extension/UIView+.swift
  Diptych/Diptych/Global/Extension/View+.swift
  Diptych/Diptych/Presentation/Archive/View/Album/AlbumListView.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CalendarScrollView.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CalendarTest/ExampleCode.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CalendarView.swift
  Diptych/Diptych/Presentation/Archive/View/Calendar/CellView.swift
  Diptych/Diptych/Presentation/Archive/View/QuestionList/QuestionListView.swift
  Diptych/Diptych/Presentation/Auth/Model/DiptychAlbum.swift
  Diptych/Diptych/Presentation/Auth/View/Auth/LoadingVerificationView.swift
  Diptych/Diptych/Presentation/Auth/View/Auth/LogInView.swift
  Diptych/Diptych/Presentation/Auth/View/Auth/SecureInputView.swift
  Diptych/Diptych/Presentation/Auth/View/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/Auth/View/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/Auth/View/Matching/ProfileSettingView.swift
  Diptych/Diptych/Presentation/Auth/ViewModel/UserViewModel.swift
  Diptych/Diptych/Presentation/Camera/View/CameraRepresentableView.swift
  Diptych/Diptych/Presentation/Camera/View/TransformImageBasedOnContainerView.swift
  Diptych/Diptych/Presentation/Camera/ViewController/BlurPopupUIView.swift
  Diptych/Diptych/Presentation/Camera/ViewController/CameraStoryboard.storyboard
  Diptych/Diptych/Presentation/Camera/ViewController/CameraViewController.swift
  Diptych/Diptych/Presentation/Camera/ViewModel/CameraViewModel.swift
  Diptych/Diptych/Presentation/Common/ArchiveTabView.swift
  Diptych/Diptych/Presentation/Common/DiptychTabView.swift
  Diptych/Diptych/Presentation/Common/DiptychTabView2.swift
  Diptych/Diptych/Presentation/Common/LottieView.swift
  Diptych/Diptych/Presentation/OnBoarding/View/OnBoardingView.swift
  Diptych/Diptych/Presentation/PhotoDetail/View/PhotoDetailView.swift
  Diptych/Diptych/Presentation/PhotoDetail/View/ShareSheetView.swift
  Diptych/Diptych/Presentation/User/Auth/.gitkeep
  Diptych/Diptych/Presentation/User/Matching/.gitkeep
  Diptych/Diptych/Presentation/User/Model/DiptychUser.swift
  Diptych/Diptych/Resources/Lottie/DiptychSplashLogo.json
  Diptych/Diptych/Resources/Lottie/DiptychSplashLogo3sec.json
  Diptych/Diptych/Resources/Lottie/LoadingLottie.json
Labels: Chore, 소다

#110 [Chore] #108 - 폴더 리네이밍 및 구조 수정
  Diptych/Diptych.xcodeproj/project.pbxproj
  Diptych/Diptych/Presentation/User/Model/DiptychAlbum.swift
  Diptych/Diptych/Presentation/User/View/Auth/LoadingVerificationView.swift
  Diptych/Diptych/Presentation/User/View/Auth/LogInView.swift
  Diptych/Diptych/Presentation/User/View/Auth/SecureInputView.swift
  Diptych/Diptych/Presentation/User/View/Auth/SignUpView.swift
  Diptych/Diptych/Presentation/User/View/Matching/CouplingView.swift
  Diptych/Diptych/Presentation/User/View/Matching/ProfileSettingView.swift
  Diptych/Diptych/Presentation/User/ViewModel/UserViewModel.swift
Labels: Chore, 소다

#114 [Fix] #113 - firebase 서버 통신 관련 오류 수정
  Diptych/Diptych/Presentation/Profile/View/ProfileView.swift
  Diptych/Diptych/Presentation/TodayDiptych/View/TodayDiptychView.swift
  Diptych/Diptych/Presentation/TodayDiptych/ViewModel/TodayDiptychViewModel.swift
Labels: Fix, 소다
